pantheon-systems/drops-7

modules/pantheon/pantheon_api/pantheon_api.module
Follow-up to #37, #38, as originally reported by @phenaproxima in #drupal-contribute
=> Fix a call to pantheon_bulk_file_delete() without a check first.

modules/pantheon/pantheon_apachesolr/pantheon_apachesolr.module
This provides out-of-the-box support for the pantheon_apachesolr module when using the upcoming Pantheon Environment on Kalabox 2. It also reduces false positives when posting the schema ie it currently reports the schema has been posted with success even with a 403 and non null response aka failing
=> Fix false positives for schema posting and kalabox support

includes/file.inc
A client that has lots and lots of Pantheon sites runs a number of mass operations on all their sites via drush. They are experiencing intermittent failures where Drupal is trying to write the `'private://.htaccess'` file, getting this error:
```
File
/srv/bindings/xxxxxxxxxxxxxxxxxxxxxxxx/code/includes/file.inc,
line 500
file_put_contents(private:///.htaccess): failed to open stream:          [error]
"DrupalPrivateStreamWrapper::stream_open" call failed
```
However, in includes/file.inc, there's code to prevent this from happening on Pantheon:
```
function file_create_htaccess($directory, $private = TRUE, $force_overwrite = FALSE) {
if (isset($_SERVER['PANTHEON_ENVIRONMENT'])) {
// Skip on Pantheon since we use nginx and this can hang.
return;
}
// ...
}
```
... except, it's using …
=> Prevent creation of .htaccess when running drush

modules/pantheon/pantheon_apachesolr/Pantheon_Apache_Solr_Service.php, modules/pantheon/pantheon_apachesolr/Pantheon_Search_Api_Solr_Service.php, modules/pantheon/pantheon_apachesolr/pantheon_apachesolr.module
Respect relative docroot when on the Pantheon platform. Make module disable itself when not running on the Pantheon environment.
Re-do of #90, which was inadvertently not merged.
=> Look up path to client certificate relative to $_ENV['HOME'] 

CHANGELOG.txt, includes/bootstrap.inc, includes/file.inc, modules/file/file.module, modules/file/tests/file.test
This PR was created by the create-update-pr script.
For more information, see https://www.drupal.org/project/drupal/releases/7.56
Instructions to test:
Create a new Drupal 7 site on Pantheon.
When site creation is finished, visit dashboard.
Switch to git mode.
Clone your site locally.
Apply the files from this PR on top of your local checkout.
git remote add drops-7 git@github.com:pantheon-systems/drops-7.git
git fetch drops-7
git merge drops-7/update-7.56
Push your files back up to Pantheon.
Switch back to sftp mode.
Visit your site. Step through the installation process. Look for any problems.
=> Update to drupal/drupal 7.56

CHANGELOG.txt, includes/bootstrap.inc, includes/request-sanitizer.inc
This PR was created by the create-update-pr script.
For more information, see https://www.drupal.org/project/drupal/releases/7.58
Instructions to test:
Create a new Drupal 7 site on Pantheon.
When site creation is finished, visit dashboard.
Switch to git mode.
Clone your site locally.
Apply the files from this PR on top of your local checkout.
git remote add drops-7 git@github.com:pantheon-systems/drops-7.git
git fetch drops-7
git merge drops-7/update-7.58
Push your files back up to Pantheon.
Switch back to sftp mode.
Visit your site. Step through the installation process. Look for any problems.
=> Update to drupal/drupal 7.58

pantheon.upstream.yml
For more information on PHP versions, see https://pantheon.io/docs/php-versions/
=> Use php version 7.1 by default for Drupal 7 sites.

modules/pantheon/pantheon_apachesolr/pantheon_apachesolr.drush.inc
=> Adding Drush Command for posting solr schema

pantheon.upstream.yml
See discussion at pantheon-systems/drops-6#26.
In the case of drops-7, PHP 7.2 has been supported since Drupal 7.61.
=> Update to PHP 7.2 by default

CHANGELOG.txt, includes/bootstrap.inc, misc/typo3/drupal-security/PharExtensionInterceptor.php
Update from Drupal 7.62 to Drupal 7.63.
- git merge drops-7/update-7.63
=> Update to Drupal 7.63. For more information, see https://www.drupal.org/project/drupal/releases/7.63

CHANGELOG.txt, includes/bootstrap.inc, includes/file.inc, modules/simpletest/tests/file.test
Update from Drupal 7.64 to Drupal 7.65.
- git merge drops-7/update-7.65
=> Update to Drupal 7.65. For more information, see https://www.drupal.org/project/drupal/releases/7.65

pantheon.upstream.yml
Enforce HTTPS by default. For more info see https://pantheon.io/blog/pantheon-now-enforces-https-default-plus-really-simple-hsts
=> [CORE-1354] Enforce HTTPS by default.

CHANGELOG.txt, includes/bootstrap.inc, includes/form.inc, modules/file/tests/file.test, modules/simpletest/tests/form.test
Update from Drupal 7.71 to Drupal 7.72.
- git merge drops-7/update-7.72
=> Update to Drupal 7.72. For more information, see https://www.drupal.org/project/drupal/releases/7.72

CHANGELOG.txt, includes/bootstrap.inc, misc/ajax.js, misc/autocomplete.js, misc/drupal.js
Update from Drupal 7.72 to Drupal 7.73.
- git merge drops-7/update-7.73
=> Update to Drupal 7.73. For more information, see https://www.drupal.org/project/drupal/releases/7.73

CHANGELOG.txt, includes/bootstrap.inc, includes/file.inc, modules/simpletest/tests/file.test, modules/simpletest/tests/file_test.module
Update from Drupal 7.73 to Drupal 7.74.
- git merge drops-7/update-7.74
=> Update to Drupal 7.74. For more information, see https://www.drupal.org/project/drupal/releases/7.74

CHANGELOG.txt, includes/bootstrap.inc, modules/system/system.tar.inc
Update from Drupal 7.74 to Drupal 7.75.
- git merge drops-7/update-7.75
=> Update to Drupal 7.75. For more information, see https://www.drupal.org/project/drupal/releases/7.75

CHANGELOG.txt, includes/bootstrap.inc, includes/common.inc, sites/default/default.settings.php
Update from Drupal 7.79 to Drupal 7.80.
- git merge drops-7/update-7.80
=> Update to Drupal 7.80. For more information, see https://www.drupal.org/project/drupal/releases/7.80

pantheon.upstream.yml
For details, see https://pantheon.io/docs/pantheon-yml#specify-a-version-of-mariadb
See also pantheon-systems/documentation#6928, which modifies that section.
=> [CMS-147] + [PRT-227] Update to PHP 7.4 and MariaDB 10.4

CHANGELOG.txt, includes/bootstrap.inc, includes/database/select.inc, modules/book/book.module
Update from Drupal 7.93 to Drupal 7.94.
- git merge drops-7/update-7.94
=> Update to Drupal 7.94. For more information, see https://www.drupal.org/project/drupal/releases/7.94

CHANGELOG.txt, includes/bootstrap.inc, modules/system/system.admin.inc
Update from Drupal 7.94 to Drupal 7.95.
- git merge drops-7/update-7.95
=> Update to Drupal 7.95. For more information, see https://www.drupal.org/project/drupal/releases/7.95

CHANGELOG.txt, includes/bootstrap.inc, includes/file.inc, modules/image/image.module, modules/system/system.module, sites/default/default.settings.php
Update from Drupal 7.95 to Drupal 7.96.
- git merge drops-7/update-7.96
=> Update to Drupal 7.96. For more information, see https://www.drupal.org/project/drupal/releases/7.96

CHANGELOG.txt, includes/bootstrap.inc, includes/file.inc, modules/system/system.module
Update from Drupal 7.96 to Drupal 7.97.
- git merge drops-7/update-7.97
=> Update to Drupal 7.97. For more information, see https://www.drupal.org/project/drupal/releases/7.97

modules/pantheon/pantheon_apachesolr/Pantheon_Apache_Solr_Service.php, modules/pantheon/pantheon_apachesolr/Pantheon_Search_Api_Solr_Service.php
Starting PHP 8.1, we started seeing the following warning from trim():
```
Deprecated function: trim(): Passing null to parameter #1 ($string) of type string is deprecated in PantheonApacheSolrService->_makeHttpRequest() (line 500 of /code/modules/pantheon/pantheon_apachesolr/Pantheon_Apache_Solr_Service.php).
```
Here we now check that the array_shifted variable is not empty first.
=> [BUGS-7554] Fix php 8.1 warning in Apache Solr module

.gitlab-ci.yml, .gitlab-ci/pipeline.yml, CHANGELOG.txt, includes/bootstrap.inc, modules/announcements_feed/announcements-feed.tpl.php, modules/announcements_feed/announcements_feed.css, modules/announcements_feed/announcements_feed.inc, modules/announcements_feed/announcements_feed.info, modules/announcements_feed/announcements_feed.install, modules/announcements_feed/announcements_feed.module, modules/announcements_feed/tests/announce_feed/community-feeds.json, modules/announcements_feed/tests/announce_feed/empty.json, modules/announcements_feed/tests/announce_feed/hacked.json, modules/announcements_feed/tests/announce_feed/invalid-feeds.json, modules/announcements_feed/tests/announce_feed/removed.json, modules/announcements_feed/tests/announce_feed/updated.json, modules/announcements_feed/tests/announce_feed_test.info, modules/announcements_feed/tests/announce_feed_test.module, modules/announcements_feed/tests/announce_feed_test.test, modules/simpletest/tests/module.test, modules/system/system.install, modules/user/user.module, modules/user/user.test, profiles/standard/standard.install
Update from Drupal 7.99 to Drupal 7.100.
- git merge drops-7/update-7.100
=> Update to Drupal 7.100. For more information, see https://www.drupal.org/project/drupal/releases/7.100

.gitlab-ci.yml, .htaccess, CHANGELOG.txt, includes/ajax.inc, includes/bootstrap.inc, includes/common.inc, includes/errors.inc, includes/file.inc, includes/unicode.inc, includes/updater.inc, modules/dblog/dblog.test, modules/node/node.admin.inc, modules/simpletest/drupal_web_test_case.php, modules/simpletest/tests/ajax.test, modules/simpletest/tests/entity_crud.test, modules/simpletest/tests/entity_crud_hook_test.module, modules/simpletest/tests/file.test, modules/simpletest/tests/form.test, modules/simpletest/tests/unicode.test, modules/system/system.admin.inc, modules/system/system.module, modules/system/system.tar.inc, modules/user/user.api.php, modules/user/user.module, modules/user/user.test, sites/default/default.settings.php
Update from Drupal 7.100 to Drupal 7.101.
- git merge drops-7/update-7.101
=> Update to Drupal 7.101. For more information, see https://www.drupal.org/project/drupal/releases/7.101

pantheon.upstream.yml
Supported as of 7.92.
https://www.drupal.org/docs/7/system-requirements/php-requirements-for-drupal-7
----
Related: https://github.com/pantheon-systems/WordPress/pull/389
https://getpantheon.atlassian.net/browse/CMSP-954
=> [CMSP-954] Update default PHP to 8.2

modules/pantheon/pantheon_apachesolr/Pantheon_Apache_Solr_Service.php
To avoid the depreciations warnings in PHP 8.2:
> Deprecated function: Creation of dynamic property PantheonApacheSolrService::$system_info_cid is deprecated in PantheonApacheSolrService->setSystemInfo() (line 149 of /code/modules/pantheon/pantheon_apachesolr/Pantheon_Apache_Solr_Service.php).
=> Added properties to the class.

modules/pantheon/pantheon_apachesolr/Pantheon_Apache_Solr_Service.php, modules/pantheon/pantheon_apachesolr/Pantheon_Search_Api_Solr_Service.php, modules/pantheon/pantheon_apachesolr/pantheon_apachesolr.info, modules/pantheon/pantheon_apachesolr/pantheon_apachesolr.module
Follows #217
- Wraps `pantheon_curl_setup` calls to accommodate running locally (i.e. lando)
- `_makeHttpRequest`'s "mimic $result object" step encountered some surprises in Lando, made more resilient
- skip setting _any_ ssl context either way when not on pantheon
- remove `pantheon_apachesolr_certs_dir` which lost any use in the last PR
=> [SITE-4307] pantheon_apachesolr: handle curl config for local development
